# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/daniel/reckziegelda74985_at_5888/ncurses

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/daniel/reckziegelda74985_at_5888/ncurses

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/daniel/reckziegelda74985_at_5888/ncurses/CMakeFiles /home/daniel/reckziegelda74985_at_5888/ncurses/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/daniel/reckziegelda74985_at_5888/ncurses/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named main

# Build rule for target.
main: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 main
.PHONY : main

# fast build rule for target.
main/fast:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/build
.PHONY : main/fast

graphics.o: graphics.cpp.o

.PHONY : graphics.o

# target to build an object file
graphics.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/graphics.cpp.o
.PHONY : graphics.cpp.o

graphics.i: graphics.cpp.i

.PHONY : graphics.i

# target to preprocess a source file
graphics.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/graphics.cpp.i
.PHONY : graphics.cpp.i

graphics.s: graphics.cpp.s

.PHONY : graphics.s

# target to generate assembly for a file
graphics.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/graphics.cpp.s
.PHONY : graphics.cpp.s

gridfont.o: gridfont.cpp.o

.PHONY : gridfont.o

# target to build an object file
gridfont.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/gridfont.cpp.o
.PHONY : gridfont.cpp.o

gridfont.i: gridfont.cpp.i

.PHONY : gridfont.i

# target to preprocess a source file
gridfont.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/gridfont.cpp.i
.PHONY : gridfont.cpp.i

gridfont.s: gridfont.cpp.s

.PHONY : gridfont.s

# target to generate assembly for a file
gridfont.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/gridfont.cpp.s
.PHONY : gridfont.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/main.cpp.s
.PHONY : main.cpp.s

scrollarea.o: scrollarea.cpp.o

.PHONY : scrollarea.o

# target to build an object file
scrollarea.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/scrollarea.cpp.o
.PHONY : scrollarea.cpp.o

scrollarea.i: scrollarea.cpp.i

.PHONY : scrollarea.i

# target to preprocess a source file
scrollarea.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/scrollarea.cpp.i
.PHONY : scrollarea.cpp.i

scrollarea.s: scrollarea.cpp.s

.PHONY : scrollarea.s

# target to generate assembly for a file
scrollarea.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/scrollarea.cpp.s
.PHONY : scrollarea.cpp.s

sound.o: sound.cpp.o

.PHONY : sound.o

# target to build an object file
sound.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/sound.cpp.o
.PHONY : sound.cpp.o

sound.i: sound.cpp.i

.PHONY : sound.i

# target to preprocess a source file
sound.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/sound.cpp.i
.PHONY : sound.cpp.i

sound.s: sound.cpp.s

.PHONY : sound.s

# target to generate assembly for a file
sound.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/sound.cpp.s
.PHONY : sound.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... main"
	@echo "... edit_cache"
	@echo "... graphics.o"
	@echo "... graphics.i"
	@echo "... graphics.s"
	@echo "... gridfont.o"
	@echo "... gridfont.i"
	@echo "... gridfont.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... scrollarea.o"
	@echo "... scrollarea.i"
	@echo "... scrollarea.s"
	@echo "... sound.o"
	@echo "... sound.i"
	@echo "... sound.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

